version: "3.7"
services:
  app:
    build:
      args:
        user: ahmadghallab
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: qruz_api
    container_name: qruz_api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: qruz_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: qruz
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    container_name: qruz_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
  
  redis:
    image: redis
    container_name: qruz_redis
    restart: unless-stopped
    volumes:
      - ./docker-compose/redis:/data

networks:
  default:
    external:
      name: qruz